config/routes.rb
Team4the::Application.routes.draw do
  resources :users
  resources :achievements
  resources :workout
  
  root :to => 'page#index'
  
  get '/login', :to => 'session#new'
  post '/login', :to => 'session#create'

  match '/logout', :to => 'session#destroy'
  get "/dashboard" => "page#dashboard"
  get "/ego-table" => "page#ego_table", :as => :ego_table
  get "/team/:id" => "teams#show", :as => :team
end

app/views/page/dashboard.html.erb
<div class="row">
	<div class="span4">
		<h3>Tabell för lagen</h3>
		<h4>Antal loggade kilometer</h4>
		<div class="alert alert-info">
			<i class="icon-info-sign"></i> Uppdateras en gång i timmen!
		</div>
		<ol>
			<% @teams.sort_by{|team| [team.average_distance, team.name] }.reverse.each do |team| %>
				<li>
					<a href="<%= url_for team_path team -%>" rel="tooltip" data-original-title="<%= team.users.map{|u| u.username + " (" + ("%.1f" % u.total_distance).to_s + " km)"  }.join("<br/>") -%>"><%= team.name -%></a> - 
					<strong>Snitt:</strong> <%= "%.2f" % team.average_distance -%> km 
					/ <strong>Totalt:</strong> <%= "%.1f" % team.total_distance -%> km
				</li>
			<% end -%>
		</ol>
		<h4>Antal träningstillfällen</h4>
		<ol>
		<% @teams.sort_by{|team| [team.average_workouts, team.name] }.reverse.each do |team|%>
			<li>
				<a href="<%= url_for team_path team -%>" rel="tooltip" data-original-title="<%= team.users.map{|u| u.username + " (" + u.workouts.count.to_s + ")" }.join("<br/>") -%>"><%= team.name -%></a> - 
				<strong>Snitt:</strong> <%= "%.2f" % team.average_workouts -%> 
				/ <strong>Totalt:</strong> <%= team.workouts -%> tillfällen
			</li>
		<% end -%>
		</ol>
		<h4>Achievementspoäng</h4>
		<ol>
			<% @teams.sort_by{|team| [team.average_achievement_points, team.name]}.reverse.each do |team|%>
			<li>
				<a href="<%= url_for team_path team -%>" rel="tooltip" data-original-title="<%= team.users.map{|u| u.username + " (" + u.total_achievement_points.to_s + "p)" }.join("<br/>") -%>"><%= team.name -%></a> - 
				<strong>Snitt:</strong> <%= "%.2f" % team.average_achievement_points -%> 
				/ <strong>Totalt:</strong> <%= team.achievement_points -%> poäng
			</li>
			<% end -%>
		</ol>
		<h4>Total ranking</h4>
		<ol>
			<% @teams.sort_by{|team| [team.total_ranking, team.name]}.each do |team| %>
				<li>
					<a href="<%= url_for team_path team -%>" rel="tooltip" data-original-title="<%= team.users.map{|u| u.username}.join("<br/>") -%>"><%= team.name -%></a> - 
					<strong>Rankingpoäng:</strong> <%= team.total_ranking -%>p
				</li>
			<% end -%>
		</ol>
	</div>
	<div class="span4">
		<h3>Achievements</h3>
		<h4>Dina avklarade achievements</h4>
		<div class="list">
		<% @achievements.each do |ach| %>
			<p>
				<%= ach[:ach].name %>
				|
				<strong><%= ach[:point] %></strong> poäng
				|
				<% if ach[:user].id == current_user.id %>
				<%= link_to 'Radera', achievement_path(ach[:aid]), method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			</p>
		<% end %>		
		</div>
		
		<h4>Avklarade achievements i ditt team</h4>
		<div class="list">
		<% @team_achievements.each do |ach| %>
			<p>
				<%= ach[:ach].name %>
				|
				<strong><%= ach[:point] %></strong> poäng
				|
				av
				<%= ach[:user].username -%>
			</p>
		<% end %>
		</div>
	</div>
	<div class="span4">
		<h3>Träningstillfällen</h3>
		<h4>Dina träningstillfällen</h4>
		<div class="list">
		<% @workouts.each do |workout| %>
			<p>
				<%= workout.description %>
				-
				<%= link_to workout.workout_date, workout %>
			</p>
		<% end %>
		</div>
		
		<h4>Träningstillfällen i ditt team</h4>
		<div class="list">
		<% @team_workouts.sort_by{|w|w.workout_date}.reverse.each do |workout| %>
			<p>
				<%= workout.description %>
				-
				<%= link_to workout.workout_date, workout %>
				av
				<%= workout.user.username -%>
			</p>
		<% end %>
		</div>
	</div>
</div>

app/views/page/ego_table.html.erb
<div class="row">
	<div class="span4">
		<h4>Antal loggade kilometer</h4>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Användare</th>
					<th>Km</th>
				</tr>
			</thead>
			<tbody>
				<% @users.sort_by {|u| [u.total_distance, u.username]}.reverse.each_with_index do |user, i| %>
					<tr>
						<td><%= i + 1 -%></td>
						<td><%= user.username -%></td>
						<td><%= "%.2f" % user.total_distance -%></td>
					</tr>	
				<% end -%>
			</tbody>
		</table>
		<div class="alert alert-info">
			OBS! Uppdateras en gång per timme
		</div>
	</div>
	<div class="span4">
		<h4>Antal träningstillfällen</h4>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Användare</th>
					<th>Antal</th>
				</tr>
			</thead>
			<tbody>
				<% @users.sort_by {|u| [u.workouts.count, u.username]}.reverse.each_with_index do |user, i| %>
					<tr>
						<td><%= i + 1 -%></td>
						<td><%= user.username -%></td>
						<td><%= user.workouts.count -%> st</td>
					</tr>	
				<% end -%>
			</tbody>
		</table>
	</div>
	<div class="span4">
		<h4>Antal achievementspoäng</h4>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Användare</th>
					<th>Poäng</th>
				</tr>
			</thead>
			<tbody>
				<% @users.sort_by {|u| [u.achievement_points.sum("point"), u.username]}.reverse.each_with_index do |user, i| %>
					<tr>
						<td><%= i + 1 -%></td>
						<td><%= user.username -%></td>
						<td><%= user.achievement_points.sum("point") -%>p</td>
					</tr>	
				<% end -%>
			</tbody>
		</table>
	</div>
</div>

app/views/page/index.html.erb
<div class="row">
  <span class="span8">
    <h3>Team 4 The Pig!</h3>
    <p>Den ultimata fitnesstävlingen 2012.</p>
  </span>
  <span class="span4">
    <h3>Logga in</h3>
    <%= render "session/form" %>
  </span>
</div>