config/routes.rb
Team4the::Application.routes.draw do
  resources :users
  resources :achievements
  resources :workout
  
  root :to => 'page#index'
  
  get '/login', :to => 'session#new'
  post '/login', :to => 'session#create'

  match '/logout', :to => 'session#destroy'
  get "/dashboard" => "page#dashboard"
  get "/ego-table" => "page#ego_table", :as => :ego_table
  get "/team/:id" => "teams#show", :as => :team
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :description, :workout_date
  belongs_to :user
  
  def user
    User.find(self.user_id)
  end
end

app/controllers/workout_controller.rb
class WorkoutController < ApplicationController
	def new
		@workout = Workout.new
		respond_to do |format|
			format.html
		end
	end
	
	def create
		@workout = Workout.new(params[:workout])
		@workout.user = current_user
		
		respond_to do |format|
			if @workout.save
				format.html { redirect_to @workout, notice: 'Workout was sucessfully created.' }
			else
				format.html { render action: 'new' }
			end
		end
	end
	
	def edit
		@workout = Workout.find(params[:id])
	end
	
	def update
		@workout = Workout.find(params[:id])
		
		respond_to do |format|
			if @workout.update_attributes(params[:workout])
				format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
			else
				format.html { render action: "edit" }
			end
		end
	end
	
	def show
		@workout = Workout.find(params[:id])
		
		respond_to do |format|
			format.html
		end	
	end
	
	def destroy
		@workout = Workout.find(params[:id])
		@workout.destroy
		respond_to do |format|
			format.html { redirect_to dashboard_path }
		end
	end
end

app/helpers/workout_helper.rb
module WorkoutHelper
end

app/views/workout/_form.html.erb
<% 
if @workout.id 
	url = workout_path
else
	url = workout_index_path
end
%>
<%= form_for(@workout, :url => url) do |f| %>
	<% if @workout.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@workout.errors.count, "error") %> hindrade detta träningstillfälle att sparas:</h2>

			<ul>
			<% @workout.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :workout_date, "Träningsdatum" %>
		<%= f.text_field :workout_date, :class => 'datepicker' %>
	</div>
	<div class="field">
		<%= f.label :description, "Beskrivning" %>
		<%= f.text_field :description %>
	</div>
	<div class="actions">
		<%= f.submit "Spara", :class => "btn" %>
	</div>
<% end %>

app/views/workout/edit.html.erb
<h3>Editing <%= @workout.description %></h3>

<%= render 'form' %>

app/views/workout/new.html.erb
<h3>Nytt träningstillfälle</h3>

<%= render "form" %>

app/views/workout/show.html.erb
<p id="notice"><%= notice %></p>
<div class="box">
	
	<% if @workout.user == current_user %>
	<p class="pull-right meta">
		<%= link_to 'Edit', edit_workout_path(@workout) %> |
		<%= link_to 'Delete', workout_path(@workout), method: :delete, data: {
			confirm: 'Are you sure?'
		}%>    
	</p>
	<% end %>
	
	<p>
		<b>Workout date:</b>
	</p>
	<p>
		<%= @workout.workout_date %>
	</p>

	<p>
		<b>Description:</b>
	</p>
	<p>
		<%= @workout.description %>
	</p>
	<div class="clear"></div>
</div>