config/routes.rb
Team4the::Application.routes.draw do
  resources :users
  resources :achievements
  resources :workout
  
  root :to => 'page#index'
  
  get '/login', :to => 'session#new'
  post '/login', :to => 'session#create'

  match '/logout', :to => 'session#destroy'
  get "/dashboard" => "page#dashboard"
  get "/ego-table" => "page#ego_table", :as => :ego_table
  get "/team/:id" => "teams#show", :as => :team
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Team 4 The Pig @ Isotop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="The coolest fitness competition, like ever.">
    <meta name="author" content="Björn Lennartsson, Fredrik Forsmo">

    <%= stylesheet_link_tag    "application", :media => "all" %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
  </head>

  <body>
  	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Team 4 The Pig @ Isotop", dashboard_path, :class => "brand" %>
          <div class="nav-collapse collapse">
            <% if is_signed_in? %>
              <ul class="nav">
                <li><%= link_to "Dashboard", dashboard_path %></li>
                <li><%= link_to "Träningstillfälle", new_workout_path %></li>
                <li><%= link_to "Achievements", achievements_path %></li>
                <li><%= link_to "Egotabellen", ego_table_path -%></li>
              </ul>
              <ul class="nav pull-right">
                <li><span style="padding:10px 15px 10px;line-height:20px;display:block;"><%= "Välkommen, #{current_user.username}!" -%></span></li>
                <li><%= link_to "Ändra din profil", edit_user_path(current_user) %>
                <li><%= link_to "Logga ut", logout_path %></li>
              </ul>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <%- flash.each do |name, msg| -%>
          <div class="<%= get_flash_class name %>">
            <a href="#" class="close" data-dismiss="alert">x</a>
            <%=raw msg %>
          </div>
      <%- end -%>
      
  		<%= yield %>
  	</div>
    <script type="text/javascript">
      $("a[rel=tooltip]").tooltip();
    </script>
  </body>
</html>